name: CI–FastAPI

on:
  pull_request:
    branches: [main, dev]
  push:
    branches: [main, dev]

permissions:
  contents: read

jobs:
  security:
    name: Dependency security check
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install safety
        run: |
          python -m pip install --upgrade pip
          pip install safety

      - name: Run safety on requirements
        run: |
          if [ -f requirements.txt ]; then safety check -r requirements.txt --full-report || true; fi
          if [ -f requirements-dev.txt ]; then safety check -r requirements-dev.txt --full-report || true; fi

  test:
    name: Unit tests + coverage
    needs: security                      # ← le job "test" dépend du job "security"
    runs-on: ubuntu-24.04
    env:
      PYTHONPATH: ${{ github.workspace }} # pour les imports "from app..."
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Run tests with coverage
        run: |
          pytest --maxfail=1 --disable-warnings -q \
                 --cov=app --cov-report=xml --cov-report=term-missing

      - name: Upload coverage.xml
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
          if-no-files-found: ignore